[project]
name = "inspackage"
version = "0.1.0"
description = "Useful tool for general inspection about some python package."
authors = [{name = "xslyr",email = "wesleysilv@gmail.com"}]
Homepage = "https://github.com/xslyr/inspackage"
Documentation = "https://github.com/xslyr/inspackage#readme"
Repository = "https://github.com/xslyr/inspackage.git"
Issues = "https://github.com/xslyr/inspackage/issues"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Utilities",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Environment :: Console",
]
requires-python = ">=3.13,<4.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
inspackage = "inspackage.cli:typer_app"

dependencies = [
    "typer[all] (>=0.21.1,<0.22.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "textual (>=7.5.0,<8.0.0)",
]

[dependency-groups]
dev = [
    "ruff (>=0.14.14,<0.15.0)",
    "pylint (>=4.0.4,<5.0.0)",
    "taskipy (>=1.14.1,<2.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
python_files = "test_*.py"
addopts = "--doctest-modules"


[tool.taskipy.tasks]
lint = "pylint inspackage"
ruff = "ruff format ./inspackage && ruff check --fix ./inspackage"
test = "pytest -v --cov=inspackage"
post_test = "coverage html"


[tool.pylint.master]
ignore-paths = ["^tests/.*$"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint."messages control"]
disable = [
    "consider-using-f-string",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-many-arguments",
    "too-many-positional-arguments",
    "redefined-builtin",
    "unused-argument",
    "too-few-public-methods",
    "too-many-branches"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E731"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
